### ISSUE TITLE
Use the same framework as the website

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkratemplate#11] opened 2021-04-21 12:52 UTC
Perhaps repeat the header from https://cynkra.com and have a separate header with the pkgdown-specific stuff underneath?

**Comment by benubah** [comment] 2021-05-04 21:17
<style>
.navbar .container, .navbar .container-fluid {
	display: -webkit-box;
	display: -ms-flexbox;
	display: flex;
	-ms-flex-wrap: wrap;
	flex-wrap: wrap;
	-webkit-box-align: center;
	-ms-flex-align: center;
	align-items: center;
	-webkit-box-pack: justify;
	-ms-flex-pack: justify;
	justify-content: space-between;
}
.navbar-default {
	background-color: #f8f8f8;
	border-color: ;
}

  .navbar-nav {
	display: -webkit-box;
	display: -ms-flexbox;
	display: flex;
	-webkit-box-orient: vertical;
	-webkit-box-direction: normal;
/*	-ms-flex-direction: column;*/
	/* flex-direction: column; */
	padding-left: 0;
	margin-bottom: 0;
	list-style: none;
}
</style>

**Comment by benubah** [comment] 2021-05-04 23:15
cynkratemplate

![image](https://user-images.githubusercontent.com/11357251/117081030-f4b0d180-ad36-11eb-93c5-c572dfcc6103.png)

**Comment by christophsax** [comment] 2021-05-05 11:58
Technically, it looks good. But I don't think that the cynkra menu should be 1:1 on a pkgdown site. Yes, we would like to do some advertisement but having the full menu there is confusing. Is the 'about' related to the package or to cynkra? 

Kirill had a two row header in mind: The first one showing the cynkra menu, just as on the website. In the second row, there would be the pkgdown header. 

Do we have a better idea? E.g., a mouse hover over the cynkra logo that shows a few points of the website?

You can also leave it until Kirill is back.

**Comment by maelle** [comment] 2022-05-12 12:43
Duplicate of #15?

**Comment by krlmlr** [comment] 2022-05-13 05:04
I now agree we shouldn't repeat the website's menu on each pkgdown site. But we should make the pkgdown sites look more like the main website, i.e. use the same framework, the same font, and a very similar layout. We can use an icon on the top left (?) to link to the homepage. Also, we could use a slightly different color scheme to subtly distinguish it from the main website?

**Comment by krlmlr** [comment] 2022-05-13 05:04
I now agree we shouldn't repeat the website's menu on each pkgdown site. But we should make the pkgdown sites look more like the main website, i.e. use the same framework, the same font, and a very similar layout. We can use an icon on the top left (?) to link to the homepage. Also, we could use a slightly different color scheme to subtly distinguish it from the main website?

**Comment by maelle** [comment] 2022-06-20 06:11
Maybe only experimental/unstable packages should get a differently coloured website?

**Comment by maelle** [comment] 2022-06-20 11:26
Maybe the source of truth should be somewhere with notes on visual identity? Which might already exist? For instance "cynkra blue".

**Comment by pat-s** [comment] 2022-08-02 02:28
Using the same framework seems hard, I also don't really see the benefit of doing so?

Aligning both theme-wise is surely a good idea. I can see mutual benefits if this task is assigned to a single person rather than split across multiple individuals.

**Comment by maelle** [comment] 2022-08-25 11:24
To start with, where could notes on visual identity live?

**Comment by pat-s** [comment] 2022-08-25 12:25
I'd say in one our CU manuals, most probably the "devops manual"?

**Comment by maelle** [comment] 2022-08-25 14:52
so not a git based thing?

**Comment by maelle** [comment] 2022-10-04 07:42
I added a section and comment in the CU general manual (might not be the best choice since I see you had mentioned the devops manual, but the page could be moved?).

Fine to close this?

**Comment by mbannert** [comment] 2022-10-05 09:30
fine, thanks @maelle .

**Closed by mbannert** 2022-10-05 09:30 UTC
